apiVersion: v1
kind: ServiceAccount
metadata:
  name: cineapi-sa
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cinefront-sa
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-sa
  namespace: default
